site_name: Tiro
repo_url: https://github.com/cap-dcwiz/Tiro
repo_name: cap-dcwiz/Tiro
watch: [tiro]
theme:
  name: material
  palette:
    primary: deep purple
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.indexes
    - navigation.prune
    - toc.follow
    - toc.integrate
nav:
  - Home: index.md
  - Get Started:
      - get_started/index.md
      - Installation: get_started/installation.md
      - Scenario: get_started/scenario.md
      - Basic Tools: get_started/basic_tools.md
      - Karez Integration: get_started/karez_integration.md
      - Utinni Integration: get_started/utinni_integration.md
  - License: license.md
  - Reference: reference/

plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: yes
            show_submodules: no


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.pathconverter
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/code_select.css