version: '3.9'

services:
  storage-influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: tiro
      DOCKER_INFLUXDB_INIT_PASSWORD: tiro_password
      DOCKER_INFLUXDB_INIT_ORG: tiro
      DOCKER_INFLUXDB_INIT_BUCKET: tiro
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: influxdb_token

  storage-arangodb:
    image: arangodb/arangodb:3.8.6
    platform: linux/amd64
    restart: always
    ports:
      - "8529:8529"
    volumes:
      - ./data/arangodb:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: arangodb_password
    command: arangod --server.endpoint tcp://0.0.0.0:8529

  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf

  nats-server:
    image: nats
    restart: always
    ports:
      - "4222:4222"

  mock-server:
    build:
      context: ..
      dockerfile: demo/tiro_mock.dockerfile
    image: tiro_mock
    restart: always
    volumes:
      - ./config:/tiro/config
    command: tiro mock serve config/scenario.yaml config/use1.yaml -h 0.0.0.0

  karze-roles:
    build:
      context: ..
      dockerfile: demo/tiro_mock.dockerfile
    image: tiro_mock
    restart: always
    volumes:
      - ./karez_plugins:/tiro/plugins
      - ./data/karez-logs:/tiro/logs
      - ./config:/tiro/config
    command: karez deploy -c config/karez_mock.yaml -p plugins -a nats://nats-server:4222
    depends_on:
      - mock-server
      - nats-server
      - storage-influxdb
      - storage-arangodb
