$asset_library_path: .
$asset_library_name: assets

Room:
    $type: data_hall.Room
    Rack:
        $type: data_hall.Rack
        $number: 10
        Server:
            $type: data_hall.Server
            $number: 2-20
            $defaults:
                CPUTemperature: 20
    Server:
        $type: data_hall.Server
        $number: 5
