- Room:
    - Rack:
        - FrontTemperature
        - BackTemperature
        - Server:
            - CPUTemperature
            - MemoryTemperature
    - Server:
        - CPUTemperature
        - MemoryTemperature
    - Temperature
    - Site
