[on_request]
influxdb_bucket = "tiro"
influxdb_measurement = "mock"

interpolate = true
interpolate_limit = 5
interpolate_value_range = [-inf, inf]

[influxdb]
url = "http://localhost:8086"
token = "influxdb_token"
org = "tiro"

[arangodb]
db_name = "tiro_test"
graph_name = "scenario"
hosts = "http://localhost:8529"
auth_info = {"password" = "arangodb_password"}
