name: doc

on:
  push:
    branches:
      - master
      - main
jobs:
  doc-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - run: poetry install --no-interaction
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - run: |
          source .venv/bin/activate
          pip install deps/*.whl
          mkdocs gh-deploy --force