name: Security Scanning

on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'    
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports

  sonarqube:
    name: sonarqube-scanning
    runs-on: ubuntu-latest
    needs: depchecktest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Upload Test results
        uses: actions/download-artifact@master
        with:
           name: Depcheck report
           path: ${{ runner.temp }}/reports
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.dependencyCheck.htmlReportPath=${{ runner.temp }}/reports/dependency-check-report.html
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
